# Generated by Django 4.1.7 on 2023-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exportation",
            fields=[
                (
                    "trimestre",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("total", models.FloatField()),
                ("minerai_de_fer", models.FloatField()),
                ("poisson", models.FloatField()),
                ("petrole_brut", models.FloatField()),
                ("Or", models.FloatField()),
                ("cuivre", models.FloatField()),
                ("autres", models.FloatField()),
            ],
        ),
    ]
