# Generated by Django 4.1.7 on 2023-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InflationMondiale",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("usa", models.FloatField()),
                ("france", models.FloatField()),
                ("allemagne", models.FloatField()),
                ("japon", models.FloatField()),
                ("royaume_uni", models.FloatField()),
                ("italie", models.FloatField()),
                ("canada", models.FloatField()),
            ],
        ),
    ]
