# Generated by Django 4.1.7 on 2023-04-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionCuivreOr",
            fields=[
                (
                    "trimestre",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("production_cuivre", models.FloatField()),
                ("or_quantite_en_oz_total", models.FloatField()),
            ],
        ),
    ]
