# Generated by Django 4.1.7 on 2023-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapturePoisson",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("pelagiques", models.FloatField()),
                ("demersaux", models.FloatField()),
                ("cephalopodes", models.FloatField()),
                ("crustaces", models.FloatField()),
                ("capture_total", models.FloatField()),
            ],
        ),
    ]
