# Generated by Django 4.1.7 on 2023-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EauElectricite",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("eau_brute", models.FloatField()),
                ("eau_nette", models.FloatField()),
                ("elect_brute", models.FloatField()),
                ("elect_nette", models.FloatField()),
            ],
        ),
    ]
