# Generated by Django 4.1.7 on 2023-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files")),
            ],
        ),
        migrations.CreateModel(
            name="MonnaieChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=20)),
                ("dolllar_des_u_e", models.FloatField()),
                ("euro", models.FloatField()),
                ("sterling", models.FloatField()),
                ("yen", models.FloatField()),
                ("dirham_marocain", models.FloatField()),
                ("dinar_tunisien", models.FloatField()),
                ("dinar_algerien", models.FloatField()),
                ("franc_cfa", models.FloatField()),
                ("dts", models.FloatField()),
            ],
        ),
    ]
