# Generated by Django 4.1.7 on 2023-03-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MonnaieChange", "0002_delete_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monnaiechange",
            old_name="dolllar_des_u_e",
            new_name="dollar_des_u_e",
        ),
    ]
