# Generated by Django 4.1.7 on 2023-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MonnaieChange", "0004_alter_monnaiechange_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="monnaiechange", name="id",),
        migrations.AlterField(
            model_name="monnaiechange",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
