# Generated by Django 4.1.7 on 2023-04-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MonnaieChange", "0005_remove_monnaiechange_id_alter_monnaiechange_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monnaiechange",
            name="date",
            field=models.DateField(blank=True, primary_key=True, serialize=False),
        ),
    ]
