# Generated by Django 4.1.7 on 2023-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MonnaieChange", "0006_alter_monnaiechange_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monnaiechange",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
