# Generated by Django 4.1.7 on 2023-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoursProdAliment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ble_eu_par_tonne", models.FloatField()),
                ("riz_eu_par_tonne", models.FloatField()),
                ("sucre_eu_par_tonne", models.FloatField()),
                ("the_eu_par_tone", models.FloatField()),
                ("ble_mu_par_tone", models.FloatField()),
                ("riz_mu_par_tonne", models.FloatField()),
                ("sucre_mu_par_tonne", models.FloatField()),
                ("the_mu_par_tone", models.FloatField()),
            ],
        ),
    ]
