# Generated by Django 4.1.7 on 2023-04-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CoursProdAliment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursprodaliment",
            old_name="ble_mu_par_tone",
            new_name="ble_mu_par_tonne",
        ),
        migrations.RenameField(
            model_name="coursprodaliment",
            old_name="the_eu_par_tone",
            new_name="the_eu_par_tonne",
        ),
        migrations.RenameField(
            model_name="coursprodaliment",
            old_name="the_mu_par_tone",
            new_name="the_mu_par_tonne",
        ),
    ]
