# Generated by Django 4.1.7 on 2023-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CoursProdAliment",
            "0002_rename_ble_mu_par_tone_coursprodaliment_ble_mu_par_tonne_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="coursprodaliment", name="id",),
        migrations.AlterField(
            model_name="coursprodaliment",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
