# Generated by Django 4.1.7 on 2023-04-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransportAerien",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("passagers_arriv", models.IntegerField()),
                ("passagers_depart", models.IntegerField()),
                ("total_passagers", models.IntegerField()),
                ("mvmt_avion_arriv", models.IntegerField()),
            ],
        ),
    ]
