# Generated by Django 4.1.7 on 2023-04-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransportAerien", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transportaerien",
            old_name="passagers_arriv",
            new_name="passagers_arrives",
        ),
    ]
