# Generated by Django 4.1.7 on 2023-04-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("INPC", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inpc",
            old_name="art_habmnt_et_chauss",
            new_name="artucles_habillement_et_chaussures",
        ),
        migrations.RenameField(
            model_name="inpc",
            old_name="log_eau_gaz_elec_et_autre_combtible",
            new_name="logement_eau_gaz_electricites_et_autre_combistible",
        ),
        migrations.RenameField(
            model_name="inpc",
            old_name="meub_art_menage_et_entre_courant_du_foyer",
            new_name="meubles_articles_de_menages_et_entretient_courant_du_foyer",
        ),
        migrations.RenameField(
            model_name="inpc",
            old_name="prod_alim_et_boiss_non_alcool_fr",
            new_name="produits_alimentaires_et_boissons_non_alcolises",
        ),
    ]
