# Generated by Django 4.1.7 on 2023-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommerceExterieur",
            fields=[
                (
                    "trimestre",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("exportations", models.FloatField()),
                ("importation", models.FloatField()),
                ("tx_couv", models.FloatField()),
            ],
        ),
    ]
