# Generated by Django 4.1.7 on 2023-04-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommerceExterieur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commerceexterieur",
            name="solde_commercial",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
