# Generated by Django 4.1.7 on 2023-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TraficTotalMaritime",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("trafic_total_tonnes", models.FloatField()),
                ("total_nombre", models.IntegerField()),
                ("port_ndb_trafic_total", models.FloatField()),
                ("port_ndb_arrive_navires_nombre", models.IntegerField()),
                ("trafic_total", models.FloatField()),
                ("nombre_total_navires", models.IntegerField()),
            ],
        ),
    ]
