# Generated by Django 4.1.7 on 2023-04-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CoursMatPrem", "0002_remove_coursmatprem_id_alter_coursmatprem_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="cours_mon_cuivre",
            new_name="cours_mondial_du_cuivre",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="cours_mon_min_fer_prem_seri",
            new_name="cours_mondiale_de_poisson",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="cours_mon_or",
            new_name="cours_mondiale_du_minerai_fer_du_premier_seri",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="cours_mon_pet",
            new_name="cours_mondiale_du_petrole",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="cours_mon_poisson",
            new_name="cours_mondiale_or",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="prix_cuivre_mr",
            new_name="prix_du_cuivre_mauritanien",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="prix_min_mr",
            new_name="prix_du_minerai_mauritanien",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="prix_or_mr",
            new_name="prix_du_petrole_mauritanien",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="prix_pet_mr",
            new_name="prix_du_poisson_mauritanien",
        ),
        migrations.RenameField(
            model_name="coursmatprem",
            old_name="prix_poisson_mr",
            new_name="prix_or_mauritanien",
        ),
    ]
