# Generated by Django 4.1.7 on 2023-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Importation",
            fields=[
                (
                    "trimestre",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("total", models.FloatField()),
                ("produits_alimentaires", models.FloatField()),
                ("cosmetiques_chimiques", models.FloatField()),
                ("produits_petroliers", models.FloatField()),
                ("materiaux_de_construction", models.FloatField()),
                ("voitures_et_pieces_detachees", models.FloatField()),
                ("equipements", models.FloatField()),
                ("autres_biens_de_consommation", models.FloatField()),
                ("autres", models.FloatField()),
            ],
        ),
    ]
